// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_cnn_2d_100s_hls_cnn_2d_100s,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.288000,HLS_SYN_LAT=6170,HLS_SYN_TPT=6148,HLS_SYN_MEM=189,HLS_SYN_DSP=0,HLS_SYN_FF=116598,HLS_SYN_LUT=106262,HLS_VERSION=2023_2}" *)

module hls_cnn_2d_100s (
        input_1_TDATA,
        layer8_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_1_TVALID,
        input_1_TREADY,
        ap_start,
        layer8_out_TVALID,
        layer8_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] input_1_TDATA;
output  [15:0] layer8_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_1_TVALID;
output   input_1_TREADY;
input   ap_start;
output   layer8_out_TVALID;
input   layer8_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_input_1_TREADY;
wire   [239:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_layer2_out_din;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_layer2_out_write;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_start;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_done;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_continue;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_idle;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_ready;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer2_out_read;
wire   [319:0] relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer3_out_din;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer3_out_write;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_start_out;
wire    relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer3_out_read;
wire   [119:0] conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer4_out_din;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer4_out_write;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_start_write;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_start;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_done;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_continue;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_idle;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_ready;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer4_out_read;
wire   [159:0] relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer5_out_din;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer5_out_write;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_start_out;
wire    relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_start_write;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_start;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_done;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_continue;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_idle;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_ready;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_start_out;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_start_write;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer5_out_read;
wire   [9:0] dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer7_out_din;
wire    dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer7_out_write;
wire    sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_start;
wire    sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_done;
wire    sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_continue;
wire    sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_idle;
wire    sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_ready;
wire    sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer7_out_read;
wire   [15:0] sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA;
wire    sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID;
wire    layer2_out_full_n;
wire   [239:0] layer2_out_dout;
wire   [8:0] layer2_out_num_data_valid;
wire   [8:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer3_out_full_n;
wire   [319:0] layer3_out_dout;
wire   [8:0] layer3_out_num_data_valid;
wire   [8:0] layer3_out_fifo_cap;
wire    layer3_out_empty_n;
wire    layer4_out_full_n;
wire   [119:0] layer4_out_dout;
wire   [8:0] layer4_out_num_data_valid;
wire   [8:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [159:0] layer5_out_dout;
wire   [8:0] layer5_out_num_data_valid;
wire   [8:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer7_out_full_n;
wire   [9:0] layer7_out_dout;
wire   [1:0] layer7_out_num_data_valid;
wire   [1:0] layer7_out_fifo_cap;
wire    layer7_out_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_din;
wire    start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_dout;
wire    start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_din;
wire    start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_dout;
wire    start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_din;
wire    start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_dout;
wire    start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_empty_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_din;
wire    start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_full_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_dout;
wire    start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_empty_n;

hls_cnn_2d_100s_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_s conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_ready),
    .input_1_TVALID(input_1_TVALID),
    .start_out(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_start_write),
    .input_1_TDATA(input_1_TDATA),
    .input_1_TREADY(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_input_1_TREADY),
    .layer2_out_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_layer2_out_write)
);

hls_cnn_2d_100s_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_s relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_full_n),
    .ap_done(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer2_out_read),
    .layer3_out_din(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer3_out_din),
    .layer3_out_num_data_valid(layer3_out_num_data_valid),
    .layer3_out_fifo_cap(layer3_out_fifo_cap),
    .layer3_out_full_n(layer3_out_full_n),
    .layer3_out_write(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer3_out_write),
    .start_out(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_start_out),
    .start_write(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_start_write)
);

hls_cnn_2d_100s_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_s conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_ready),
    .layer3_out_dout(layer3_out_dout),
    .layer3_out_num_data_valid(layer3_out_num_data_valid),
    .layer3_out_fifo_cap(layer3_out_fifo_cap),
    .layer3_out_empty_n(layer3_out_empty_n),
    .layer3_out_read(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer3_out_read),
    .layer4_out_din(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer4_out_write),
    .start_out(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_start_write)
);

hls_cnn_2d_100s_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_s relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_full_n),
    .ap_done(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer4_out_read),
    .layer5_out_din(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer5_out_write),
    .start_out(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_start_out),
    .start_write(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_start_write)
);

hls_cnn_2d_100s_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_s dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_start),
    .start_full_n(start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_full_n),
    .ap_done(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_ready),
    .start_out(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_start_out),
    .start_write(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_start_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer5_out_read),
    .layer7_out_din(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer7_out_din),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer7_out_write)
);

hls_cnn_2d_100s_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_s sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_start),
    .ap_done(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_done),
    .ap_continue(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_continue),
    .ap_idle(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_idle),
    .ap_ready(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_ready),
    .layer7_out_dout(layer7_out_dout),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer7_out_empty_n(layer7_out_empty_n),
    .layer7_out_read(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer7_out_read),
    .layer8_out_TDATA(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA),
    .layer8_out_TVALID(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID),
    .layer8_out_TREADY(layer8_out_TREADY)
);

hls_cnn_2d_100s_fifo_w240_d247_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer2_out_read)
);

hls_cnn_2d_100s_fifo_w320_d247_A layer3_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer3_out_din),
    .if_full_n(layer3_out_full_n),
    .if_write(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_layer3_out_write),
    .if_dout(layer3_out_dout),
    .if_num_data_valid(layer3_out_num_data_valid),
    .if_fifo_cap(layer3_out_fifo_cap),
    .if_empty_n(layer3_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer3_out_read)
);

hls_cnn_2d_100s_fifo_w120_d238_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer4_out_read)
);

hls_cnn_2d_100s_fifo_w160_d238_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer5_out_read)
);

hls_cnn_2d_100s_fifo_w10_d1_S layer7_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer7_out_din),
    .if_full_n(layer7_out_full_n),
    .if_write(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_layer7_out_write),
    .if_dout(layer7_out_dout),
    .if_num_data_valid(layer7_out_num_data_valid),
    .if_fifo_cap(layer7_out_fifo_cap),
    .if_empty_n(layer7_out_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer7_out_read)
);

hls_cnn_2d_100s_start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0 start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_empty_n),
    .if_read(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_ready)
);

hls_cnn_2d_100s_start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4fYi start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4fYi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_full_n),
    .if_write(relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_ready)
);

hls_cnn_2d_100s_start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0 start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_empty_n),
    .if_read(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_ready)
);

hls_cnn_2d_100s_start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0 start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_full_n),
    .if_write(relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_empty_n),
    .if_read(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_ready)
);

hls_cnn_2d_100s_start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0 start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_din),
    .if_full_n(start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_full_n),
    .if_write(dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_start_write),
    .if_dout(start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_dout),
    .if_empty_n(start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_ready)
);

assign ap_done = sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_done;

assign ap_idle = (sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_idle & relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_idle & relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_idle & dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_idle & conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_idle & conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_idle);

assign ap_ready = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_ap_start = ap_start;

assign conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_empty_n;

assign dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_ap_start = start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_empty_n;

assign input_1_TREADY = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_U0_input_1_TREADY;

assign layer8_out_TDATA = sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer8_out_TDATA;

assign layer8_out_TVALID = sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_layer8_out_TVALID;

assign relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_ap_start = start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_empty_n;

assign relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_ap_start = start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_empty_n;

assign sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_continue = 1'b1;

assign sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_ap_start = start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_empty_n;

assign start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0_din = 1'b1;

assign start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "hls_cnn_2d_100s_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "hls_cnn_2d_100s_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //hls_cnn_2d_100s

