# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-1021525-dell-OptiPlex-7050/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xcku5p-ffvb676-2-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_12ns_28_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_sparsemux_69_6_16_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_flow_control_loop_pipe_sequential_init.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_s_sigmoid_table_ROeOg.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_16s_30_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_fifo_w240_d247_A.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_start_for_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_U0.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_regslice_both.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_relu_array_ap_fixed_20u_array_ap_fixed_16_2_5_3_0_20u_relu_config3_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_s_w7_ROM_AUTO_1R.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_start_for_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_U0.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_15s_30_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_dense_latency_ap_fixed_16_2_5_3_0_ap_fixed_12_2_5_3_0_config2_mult_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_start_for_sigmoid_array_array_ap_fixed_16_2_5_3_0_1u_sigmoid_config8_U0.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_13s_29_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_flow_control_loop_pipe.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_fifo_w160_d238_A.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_11s_27_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_dense_array_array_ap_fixed_10_6_5_3_0_1u_config7_Pipeline_DataPrepare.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_12_2_5_3_0_20u_config2_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_fifo_w10_d1_S.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_14s_29_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_12s_27_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_12s_28_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_dense_array_ap_fixed_10u_array_ap_fixed_10_6_5_3_0_1u_config7_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_dense_latency_ap_fixed_16_2_5_3_0_ap_fixed_12_2_5_3_0_config4_mult_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_13ns_29_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_fifo_w320_d247_A.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_14ns_30_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_compute_output_buffer_2d_array_array_ap_fixed_12_2_5_3_0_20u_config2_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_14s_30_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_start_for_conv_2d_cl_array_ap_fixed_20u_array_ap_fixed_12_2_5_3_0_10u_config4fYi.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_shift_line_buffer_array_ap_fixed_16_2_5_3_0_1u_config2_s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_start_for_relu_array_ap_fixed_10u_array_ap_fixed_16_2_5_3_0_10u_relu_config5_U0.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_13s_28_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_mul_16s_15s_31_1_1.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_fifo_w120_d238_A.vhd
      /home/albertu/Works/hls_cnn_2d_100s/hls_cnn_2d_100s_prj/solution1/syn/vhdl/hls_cnn_2d_100s_shift_line_buffer_array_ap_fixed_16_2_5_3_0_1u_config2_s_void_conv_2d_buffer_bkb.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top hls_cnn_2d_100s
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-1021525-dell-OptiPlex-7050/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-1021525-dell-OptiPlex-7050/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
