# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/work1/Work/CNN_iCube_FPGA_b/CNN_iCube_FPGA_b1/CNN_iCube_FPGA_b1.srcs/sources_1/ip/hls_cnn_2d_100s_0/hls_cnn_2d_100s_0.xci
# IP: The module: 'hls_cnn_2d_100s_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/work1/Work/CNN_iCube_FPGA_b/CNN_iCube_FPGA_b1/CNN_iCube_FPGA_b1.gen/sources_1/ip/hls_cnn_2d_100s_0/constraints/hls_cnn_2d_100s_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hls_cnn_2d_100s_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/work1/Work/CNN_iCube_FPGA_b/CNN_iCube_FPGA_b1/CNN_iCube_FPGA_b1.srcs/sources_1/ip/hls_cnn_2d_100s_0/hls_cnn_2d_100s_0.xci
# IP: The module: 'hls_cnn_2d_100s_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/work1/Work/CNN_iCube_FPGA_b/CNN_iCube_FPGA_b1/CNN_iCube_FPGA_b1.gen/sources_1/ip/hls_cnn_2d_100s_0/constraints/hls_cnn_2d_100s_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hls_cnn_2d_100s_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
